theme = "docuapi"
languageCode = "en-us"
baseurl = "https://umarcor.github.io/issue-runner/"
title = "issue-runner"

disableKinds = ["taxonomyTerm"]

# Code higlighting settings
pygmentsCodefences = true
pygmentsCodeFencesGuesSsyntax = false
pygmentsOptions = ""
pygmentsStyle = "monokai"
pygmentsUseClasses = false

defaultContentLanguage = "en"

[module]
[module.hugoVersion]
[[module.imports]]
# We need one module import for Hugo to detect us as a Hugo Module.
path="github.com/bep/empty-hugo-module"

[params]
search = true

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "github-ascii"
    [markup.goldmark.renderer]
      unsafe= true

[languages]
  [languages.en]
    languageName = "English"
    weight = 2
    title = "issue-runner documentation"
    toc_footers = [
      "[![github.com/umarcor/issue-runner](https://img.shields.io/badge/-umarcor/issue--runner-323131.svg?logo=github&style=flat-square&longCache=true)](https://github.com/umarcor/issue-runner)",
      "Built with [Hugo](https://gohugo.io/) theme [DocuAPI](https://github.com/bep/docuapi) by [bep](https://github.com/bep)"
    ]
    [languages.en.blackfriday]
      angledQuotes = false
      hrefTargetBlank = true
